/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewAnalysisRouteImport } from './routes/new-analysis'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SampleAnalysisRouteImport } from './routes/sample-analysis'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AnalysisAnalysisIdRouteImport } from './routes/analysis.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAnalysisRoute = NewAnalysisRouteImport.update({
  id: '/new-analysis',
  path: '/new-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleAnalysisRoute = SampleAnalysisRouteImport.update({
  id: '/sample-analysis',
  path: '/sample-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisAnalysisIdRoute = AnalysisAnalysisIdRouteImport.update({
  id: '/analysis/$analysisId',
  path: '/analysis/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/reports': typeof ReportsRoute
  '/sample-analysis': typeof SampleAnalysisRoute
  '/signup': typeof SignupRoute
  '/analysis/$analysisId': typeof AnalysisAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/reports': typeof ReportsRoute
  '/sample-analysis': typeof SampleAnalysisRoute
  '/signup': typeof SignupRoute
  '/analysis/$analysisId': typeof AnalysisAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/reports': typeof ReportsRoute
  '/sample-analysis': typeof SampleAnalysisRoute
  '/signup': typeof SignupRoute
  '/analysis/$analysisId': typeof AnalysisAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/architecture'
    | '/builder'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/new-analysis'
    | '/reports'
    | '/sample-analysis'
    | '/signup'
    | '/analysis/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/architecture'
    | '/builder'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/new-analysis'
    | '/reports'
    | '/sample-analysis'
    | '/signup'
    | '/analysis/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/architecture'
    | '/builder'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/new-analysis'
    | '/reports'
    | '/sample-analysis'
    | '/signup'
    | '/analysis/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BuilderRoute: typeof BuilderRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NewAnalysisRoute: typeof NewAnalysisRoute
  ReportsRoute: typeof ReportsRoute
  SampleAnalysisRoute: typeof SampleAnalysisRoute
  SignupRoute: typeof SignupRoute
  AnalysisAnalysisIdRoute: typeof AnalysisAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-analysis': {
      id: '/new-analysis'
      path: '/new-analysis'
      fullPath: '/new-analysis'
      preLoaderRoute: typeof NewAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-analysis': {
      id: '/sample-analysis'
      path: '/sample-analysis'
      fullPath: '/sample-analysis'
      preLoaderRoute: typeof SampleAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$analysisId': {
      id: '/analysis/$analysisId'
      path: '/analysis/$analysisId'
      fullPath: '/analysis/$analysisId'
      preLoaderRoute: typeof AnalysisAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArchitectureRoute: ArchitectureRoute,
  BuilderRoute: BuilderRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NewAnalysisRoute: NewAnalysisRoute,
  ReportsRoute: ReportsRoute,
  SampleAnalysisRoute: SampleAnalysisRoute,
  SignupRoute: SignupRoute,
  AnalysisAnalysisIdRoute: AnalysisAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
